package nexiapi

import (
	"net/url"
)

// ErrorDto struct for Error
type ErrorDto struct {
	// The time at which the error occurred.
	Timestamp string `json:"timestamp"`
	// An internal trace id assigned to the error. Used to find logs associated with errors across our services. Display to the user as something to communicate to us with inquiries about the error.
	RequestId string `json:"requestid"`
	// A keyed description of the error. We do not write human readable text here because the user interface will be multi language.  At this time, there are these values: - paylink.parse.error (json body parse error) - paylink.data.invalid (field data failed to validate, see details for more information) - paylink.id.notfound (no such paylink number in the Nexi service) - paylink.id.invalid (syntactically invalid paylink id, must be positive integer) - auth.unauthorized (token missing completely or invalid) - auth.forbidden (permissions missing)
	Message string `json:"message"`
	// Optional list of additional details about the error. If available, will usually contain English language technobabble.
	Details url.Values `json:"details,omitempty"`
}

// HealthReportDto struct for HealthReportDto
type HealthReportDto struct {
	// Health status of this service.
	Status string `json:"status"`
}

// PaymentLinkRequestDto struct for addPaymentLink request
type PaymentLinkRequestDto struct {
	// The reference ID for this payment, as generated by the Payment service
	ReferenceId string `json:"reference_id"`
	// The badge number of the attendee. Will be used to build appropriate description, referenceId, etc.
	DebitorId uint64 `json:"debitor_id"`
	// The page title to be shown on the payment page.
	AmountDue int32 `json:"amount_due"`
	// Only used in responses. The total amount paid. TODO - is this Cents or Euros?
	Currency string `json:"currency"`
	// The applicable VAT, in percent.
	VatRate float64 `json:"vat_rate"`
}

// PaymentLinkDto struct for addPaymentLink response
type PaymentLinkDto struct {
	// The page title to be shown on the payment page.
	Title string `json:"title"`
	// The description to be shown on the payment page.
	Description string `json:"description"`
	// Internal reference number for this payment process.
	ReferenceId string `json:"reference_id"`
	// The purpose of this payment process.
	Purpose string `json:"purpose"`
	// The amount to bill for in the smallest denomination.
	AmountDue int64 `json:"amount_due"`
	// Only used in responses. The total amount paid in the smallest denomination.
	AmountPaid int64 `json:"amount_paid"`
	// The currency to use, 3-letter code
	Currency string `json:"currency"`
	// The applicable VAT, in percent.
	VatRate float64 `json:"vat_rate"`
	// The payment link.
	Link string `json:"link"`
}

// PaymentDto struct for getPaymentByRefId response
type PaymentDto struct {
	// Paygate payment id
	Id string `json:"id"`
	// Internal reference number for this payment process.
	ReferenceId string `json:"reference_id"`
	// The amount to bill for in the smallest denomination.
	AmountDue int64 `json:"amount_due"`
	// Only used in responses. The total amount paid in the smallest denomination.
	AmountPaid int64 `json:"amount_paid"`
	// The currency to use, 3-letter code
	Currency string `json:"currency"`
	// Status as received from Paygate. OK, AUTHORIZED, FAILED, ...
	Status string `json:"status"`
	// ResponseCode as received from Paygate, 8 digit response code, 00000000 for success, other codes see documentation.
	ResponseCode string `json:"response_code"`
	// PaymentMethod as received from Paygate, CARD, GOOGLEPAY, APPLEPAY, ...
	PaymentMethod string `json:"payment_method"`
}
